automation:
  - id: server_fan_speed_change
    alias: Server Fan Speed Change
    trigger:
    - platform: numeric_state
      entity_id: sensor.server_temperature
      above: 26
    - platform: numeric_state
      entity_id: sensor.server_temperature
      below: 28
    - platform: numeric_state
      entity_id: sensor.server_temperature
      above: 28
    - platform: numeric_state
      entity_id: sensor.server_temperature
      below: 30
    - platform: numeric_state
      entity_id: sensor.server_temperature
      above: 30
    condition:
      condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.server_temperature
        above: 26
    action:
    - service: fan.turn_on
      entity_id: fan.server_fan
    - service: fan.set_percentage
      entity_id: fan.server_fan
      data_template:
        percentage: '{% set temp = states(''sensor.server_temperature'')|float %} {%
          if temp < 28 %} 85 {% elif temp < 30 %} 92 {% else %} 100 {% endif %}'
  - id: server_fan_off
    alias: Server Fan Off
    trigger:
    - platform: numeric_state
      entity_id: sensor.server_temperature
      below: 26
    condition: []
    action:
    - service: fan.turn_off
      entity_id: fan.server_fan
  - id: amp_fan_speed_change
    alias: Amp Fan Speed Change
    trigger:
    - platform: numeric_state
      entity_id: sensor.amp_temperature
      above: 27
    - platform: numeric_state
      entity_id: sensor.amp_temperature
      below: 30
    - platform: numeric_state
      entity_id: sensor.amp_temperature
      above: 30
    - platform: numeric_state
      entity_id: sensor.amp_temperature
      below: 32
    - platform: numeric_state
      entity_id: sensor.amp_temperature
      above: 32
    condition:
      condition: and
      conditions:
      - condition: numeric_state
        entity_id: sensor.amp_temperature
        above: 27
    action:
    - service: fan.turn_on
      entity_id: fan.amp_fan
    - service: fan.set_percentage
      entity_id: fan.amp_fan
      data_template:
        percentage: '{% set temp = states(''sensor.amp_temperature'')|float %} {% if temp
          < 30 %} 1 {% elif temp < 32 %} 20 {% else %} 100 {% endif %}'
  - id: amp_fan_off
    alias: Amp Fan Off
    trigger:
    - platform: numeric_state
      entity_id: sensor.amp_temperature
      below: 27
    condition: []
    action:
    - service: fan.turn_off
      data:
        entity_id: fan.amp_fan
