automation:
  - id: tesla_solar_charging_start
    alias: Tesla Solar Charging Start
    trigger:
    - platform: numeric_state
      entity_id: sensor.energy_meter_ct1_amps
      above: '5'
      for: 00:05:00
    condition:
    - condition: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.lucy_battery_sensor
      below: 60
    action:
    - service: switch.turn_on
      data:
        entity_id:
        - switch.lucy_charger_switch
    - service: tesla_custom.api
      data:
        command: CHARGING_AMPS
        parameters:
          path_vars:
            vehicle_id: '{{ state_attr(''binary_sensor.lucy_online_sensor'', ''id'') }}'
          charging_amps: '5'

  - id: tesla_plugged_in
    alias: Tesla Plugged In
    trigger:
    - platform: state
      entity_id: binary_sensor.tesla_wall_connector_vehicle_connected
    condition:
    - condition: numeric_state
      entity_id: sensor.lucy_battery_sensor
      below: 60
    action:
    - service: tesla_custom.api
      data:
        command: CHARGING_AMPS
        parameters:
          path_vars:
            vehicle_id: '{{ state_attr(''binary_sensor.lucy_online_sensor'', ''id'') }}'
          charging_amps: '5'